[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "client/build"
  functions = "server"

[build.environment]
  CI = "false"
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_VERSION = "18"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  functions = "server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
